# Generated by Django 2.1.7 on 2019-03-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_logog',
            new_name='album_logo',
        ),
    ]
